---

- name: "Start and Enable cloudflared service"
  ansible.builtin.service:
    name: "{{ cloudflared_service_name }}"
    state: started
    enabled: true

- name: "Restart cloudflared service"
  ansible.builtin.service:
    name: "{{ cloudflared_service_name }}"
    state: restarted
  when:
    - not ansible_check_mode
    - cloudflared_service_name in services
